/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/character.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
        position={[0, 6.3, 0]}
      >
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          material={materials.phong1}
          geometry={nodes.Ch34.geometry}
          skeleton={nodes.Ch34.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/character.glb");
