/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Grenfell_Tower_Selection_Areas.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={nodes['201'].material} geometry={nodes['201'].geometry} position={[6.67, 70.18, 0]} />
      <mesh material={nodes['202'].material} geometry={nodes['202'].geometry} position={[4.73, 70.18, 6.39]} />
      <mesh material={nodes['203'].material} geometry={nodes['203'].geometry} position={[-4.55, 70.18, 6.39]} />
      <mesh material={nodes['204'].material} geometry={nodes['204'].geometry} position={[-6.5, 70.18, 0.02]} />
      <mesh material={nodes['205'].material} geometry={nodes['205'].geometry} position={[-4.55, 70.18, -6.34]} />
      <mesh material={nodes['206'].material} geometry={nodes['206'].geometry} position={[4.73, 70.18, -6.34]} />
      <mesh material={nodes.L23.material} geometry={nodes.L23.geometry} position={[0.09, 70.18, 0.01]} />
      <mesh material={nodes.LF23.material} geometry={nodes.LF23.geometry} position={[-2.79, 70.18, 0.02]} />
      <mesh material={nodes.S23.material} geometry={nodes.S23.geometry} position={[2.98, 70.18, -0.03]} />
      <mesh material={nodes['191'].material} geometry={nodes['191'].geometry} position={[6.67, 67.58, 0]} />
      <mesh material={nodes['192'].material} geometry={nodes['192'].geometry} position={[4.73, 67.58, 6.39]} />
      <mesh material={nodes['193'].material} geometry={nodes['193'].geometry} position={[-4.55, 67.58, 6.39]} />
      <mesh material={nodes['194'].material} geometry={nodes['194'].geometry} position={[-6.5, 67.58, 0.02]} />
      <mesh material={nodes['195'].material} geometry={nodes['195'].geometry} position={[-4.55, 67.58, -6.34]} />
      <mesh material={nodes['196'].material} geometry={nodes['196'].geometry} position={[4.73, 67.58, -6.34]} />
      <mesh material={nodes.L22.material} geometry={nodes.L22.geometry} position={[0.09, 67.58, 0.01]} />
      <mesh material={nodes.LF22.material} geometry={nodes.LF22.geometry} position={[-2.79, 67.58, 0.02]} />
      <mesh material={nodes.S22.material} geometry={nodes.S22.geometry} position={[2.98, 67.58, -0.03]} />
      <mesh material={nodes['181'].material} geometry={nodes['181'].geometry} position={[6.67, 64.98, 0]} />
      <mesh material={nodes['182'].material} geometry={nodes['182'].geometry} position={[4.73, 64.98, 6.39]} />
      <mesh material={nodes['183'].material} geometry={nodes['183'].geometry} position={[-4.55, 64.98, 6.39]} />
      <mesh material={nodes['184'].material} geometry={nodes['184'].geometry} position={[-6.5, 64.98, 0.02]} />
      <mesh material={nodes['185'].material} geometry={nodes['185'].geometry} position={[-4.55, 64.98, -6.34]} />
      <mesh material={nodes['186'].material} geometry={nodes['186'].geometry} position={[4.73, 64.98, -6.34]} />
      <mesh material={nodes.L21.material} geometry={nodes.L21.geometry} position={[0.09, 64.98, 0.01]} />
      <mesh material={nodes.LF21.material} geometry={nodes.LF21.geometry} position={[-2.79, 64.98, 0.02]} />
      <mesh material={nodes.S21.material} geometry={nodes.S21.geometry} position={[2.98, 64.98, -0.03]} />
      <mesh material={nodes['171'].material} geometry={nodes['171'].geometry} position={[6.67, 62.38, 0]} />
      <mesh material={nodes['172'].material} geometry={nodes['172'].geometry} position={[4.73, 62.38, 6.39]} />
      <mesh material={nodes['173'].material} geometry={nodes['173'].geometry} position={[-4.55, 62.38, 6.39]} />
      <mesh material={nodes['174'].material} geometry={nodes['174'].geometry} position={[-6.5, 62.38, 0.02]} />
      <mesh material={nodes['175'].material} geometry={nodes['175'].geometry} position={[-4.55, 62.38, -6.34]} />
      <mesh material={nodes['176'].material} geometry={nodes['176'].geometry} position={[4.73, 62.38, -6.34]} />
      <mesh material={nodes.L20.material} geometry={nodes.L20.geometry} position={[0.09, 62.38, 0.01]} />
      <mesh material={nodes.LF20.material} geometry={nodes.LF20.geometry} position={[-2.79, 62.38, 0.02]} />
      <mesh material={nodes.S20.material} geometry={nodes.S20.geometry} position={[2.98, 62.38, -0.03]} />
      <mesh material={nodes['161'].material} geometry={nodes['161'].geometry} position={[6.67, 59.78, 0]} />
      <mesh material={nodes['162'].material} geometry={nodes['162'].geometry} position={[4.73, 59.78, 6.39]} />
      <mesh material={nodes['163'].material} geometry={nodes['163'].geometry} position={[-4.55, 59.78, 6.39]} />
      <mesh material={nodes['164'].material} geometry={nodes['164'].geometry} position={[-6.5, 59.78, 0.02]} />
      <mesh material={nodes['165'].material} geometry={nodes['165'].geometry} position={[-4.55, 59.78, -6.34]} />
      <mesh material={nodes['166'].material} geometry={nodes['166'].geometry} position={[4.73, 59.78, -6.34]} />
      <mesh material={nodes.L19.material} geometry={nodes.L19.geometry} position={[0.09, 59.78, 0.01]} />
      <mesh material={nodes.LF19.material} geometry={nodes.LF19.geometry} position={[-2.79, 59.78, 0.02]} />
      <mesh material={nodes.S19.material} geometry={nodes.S19.geometry} position={[2.98, 59.78, -0.03]} />
      <mesh material={nodes['151'].material} geometry={nodes['151'].geometry} position={[6.67, 57.18, 0]} />
      <mesh material={nodes['152'].material} geometry={nodes['152'].geometry} position={[4.73, 57.18, 6.39]} />
      <mesh material={nodes['153'].material} geometry={nodes['153'].geometry} position={[-4.55, 57.18, 6.39]} />
      <mesh material={nodes['154'].material} geometry={nodes['154'].geometry} position={[-6.5, 57.18, 0.02]} />
      <mesh material={nodes['155'].material} geometry={nodes['155'].geometry} position={[-4.55, 57.18, -6.34]} />
      <mesh material={nodes['156'].material} geometry={nodes['156'].geometry} position={[4.73, 57.18, -6.34]} />
      <mesh material={nodes.L18.material} geometry={nodes.L18.geometry} position={[0.09, 57.18, 0.01]} />
      <mesh material={nodes.LF18.material} geometry={nodes.LF18.geometry} position={[-2.79, 57.18, 0.02]} />
      <mesh material={nodes.S18.material} geometry={nodes.S18.geometry} position={[2.98, 57.18, -0.03]} />
      <mesh material={nodes['141'].material} geometry={nodes['141'].geometry} position={[6.67, 54.58, 0]} />
      <mesh material={nodes['142'].material} geometry={nodes['142'].geometry} position={[4.73, 54.58, 6.39]} />
      <mesh material={nodes['143'].material} geometry={nodes['143'].geometry} position={[-4.55, 54.58, 6.39]} />
      <mesh material={nodes['144'].material} geometry={nodes['144'].geometry} position={[-6.5, 54.58, 0.02]} />
      <mesh material={nodes['145'].material} geometry={nodes['145'].geometry} position={[-4.55, 54.58, -6.34]} />
      <mesh material={nodes['146'].material} geometry={nodes['146'].geometry} position={[4.73, 54.58, -6.34]} />
      <mesh material={nodes.L17.material} geometry={nodes.L17.geometry} position={[0.09, 54.58, 0.01]} />
      <mesh material={nodes.LF17.material} geometry={nodes.LF17.geometry} position={[-2.79, 54.58, 0.02]} />
      <mesh material={nodes.S17.material} geometry={nodes.S17.geometry} position={[2.98, 54.58, -0.03]} />
      <mesh material={nodes['131'].material} geometry={nodes['131'].geometry} position={[6.67, 51.98, 0]} />
      <mesh material={nodes['132'].material} geometry={nodes['132'].geometry} position={[4.73, 51.98, 6.39]} />
      <mesh material={nodes['133'].material} geometry={nodes['133'].geometry} position={[-4.55, 51.98, 6.39]} />
      <mesh material={nodes['134'].material} geometry={nodes['134'].geometry} position={[-6.5, 51.98, 0.02]} />
      <mesh material={nodes['135'].material} geometry={nodes['135'].geometry} position={[-4.55, 51.98, -6.34]} />
      <mesh material={nodes['136'].material} geometry={nodes['136'].geometry} position={[4.73, 51.98, -6.34]} />
      <mesh material={nodes.L16.material} geometry={nodes.L16.geometry} position={[0.09, 51.98, 0.01]} />
      <mesh material={nodes.LF16.material} geometry={nodes.LF16.geometry} position={[-2.79, 51.98, 0.02]} />
      <mesh material={nodes.S16.material} geometry={nodes.S16.geometry} position={[2.98, 51.98, -0.03]} />
      <mesh material={nodes['121'].material} geometry={nodes['121'].geometry} position={[6.67, 49.38, 0]} />
      <mesh material={nodes['122'].material} geometry={nodes['122'].geometry} position={[4.73, 49.38, 6.39]} />
      <mesh material={nodes['123'].material} geometry={nodes['123'].geometry} position={[-4.55, 49.38, 6.39]} />
      <mesh material={nodes['124'].material} geometry={nodes['124'].geometry} position={[-6.5, 49.38, 0.02]} />
      <mesh material={nodes['125'].material} geometry={nodes['125'].geometry} position={[-4.55, 49.38, -6.34]} />
      <mesh material={nodes['126'].material} geometry={nodes['126'].geometry} position={[4.73, 49.38, -6.34]} />
      <mesh material={nodes.L15.material} geometry={nodes.L15.geometry} position={[0.09, 49.38, 0.01]} />
      <mesh material={nodes.LF15.material} geometry={nodes.LF15.geometry} position={[-2.79, 49.38, 0.02]} />
      <mesh material={nodes.S15.material} geometry={nodes.S15.geometry} position={[2.98, 49.38, -0.03]} />
      <mesh material={nodes['111'].material} geometry={nodes['111'].geometry} position={[6.67, 46.78, 0]} />
      <mesh material={nodes['112'].material} geometry={nodes['112'].geometry} position={[4.73, 46.78, 6.39]} />
      <mesh material={nodes['113'].material} geometry={nodes['113'].geometry} position={[-4.55, 46.78, 6.39]} />
      <mesh material={nodes['114'].material} geometry={nodes['114'].geometry} position={[-6.5, 46.78, 0.02]} />
      <mesh material={nodes['115'].material} geometry={nodes['115'].geometry} position={[-4.55, 46.78, -6.34]} />
      <mesh material={nodes['116'].material} geometry={nodes['116'].geometry} position={[4.73, 46.78, -6.34]} />
      <mesh material={nodes.L14.material} geometry={nodes.L14.geometry} position={[0.09, 46.78, 0.01]} />
      <mesh material={nodes.LF14.material} geometry={nodes.LF14.geometry} position={[-2.79, 46.78, 0.02]} />
      <mesh material={nodes.S14.material} geometry={nodes.S14.geometry} position={[2.98, 46.78, -0.03]} />
      <mesh material={nodes['101'].material} geometry={nodes['101'].geometry} position={[6.67, 44.18, 0]} />
      <mesh material={nodes['102'].material} geometry={nodes['102'].geometry} position={[4.73, 44.18, 6.39]} />
      <mesh material={nodes['103'].material} geometry={nodes['103'].geometry} position={[-4.55, 44.18, 6.39]} />
      <mesh material={nodes['104'].material} geometry={nodes['104'].geometry} position={[-6.5, 44.18, 0.02]} />
      <mesh material={nodes['105'].material} geometry={nodes['105'].geometry} position={[-4.55, 44.18, -6.34]} />
      <mesh material={nodes['106'].material} geometry={nodes['106'].geometry} position={[4.73, 44.18, -6.34]} />
      <mesh material={nodes.L13.material} geometry={nodes.L13.geometry} position={[0.09, 44.18, 0.01]} />
      <mesh material={nodes.LF13.material} geometry={nodes.LF13.geometry} position={[-2.79, 44.18, 0.02]} />
      <mesh material={nodes.S31.material} geometry={nodes.S31.geometry} position={[2.98, 44.18, -0.03]} />
      <mesh material={nodes['091'].material} geometry={nodes['091'].geometry} position={[6.67, 41.58, 0]} />
      <mesh material={nodes['092'].material} geometry={nodes['092'].geometry} position={[4.73, 41.58, 6.39]} />
      <mesh material={nodes['093'].material} geometry={nodes['093'].geometry} position={[-4.55, 41.58, 6.39]} />
      <mesh material={nodes['094'].material} geometry={nodes['094'].geometry} position={[-6.5, 41.58, 0.02]} />
      <mesh material={nodes['095'].material} geometry={nodes['095'].geometry} position={[-4.55, 41.58, -6.34]} />
      <mesh material={nodes['096'].material} geometry={nodes['096'].geometry} position={[4.73, 41.58, -6.34]} />
      <mesh material={nodes.L12.material} geometry={nodes.L12.geometry} position={[0.09, 41.58, 0.01]} />
      <mesh material={nodes.LF12.material} geometry={nodes.LF12.geometry} position={[-2.79, 41.58, 0.02]} />
      <mesh material={nodes.S12.material} geometry={nodes.S12.geometry} position={[2.98, 41.58, -0.03]} />
      <mesh material={nodes['081'].material} geometry={nodes['081'].geometry} position={[6.67, 38.98, 0]} />
      <mesh material={nodes['082'].material} geometry={nodes['082'].geometry} position={[4.73, 38.98, 6.39]} />
      <mesh material={nodes['083'].material} geometry={nodes['083'].geometry} position={[-4.55, 38.98, 6.39]} />
      <mesh material={nodes['084'].material} geometry={nodes['084'].geometry} position={[-6.5, 38.98, 0.02]} />
      <mesh material={nodes['085'].material} geometry={nodes['085'].geometry} position={[-4.55, 38.98, -6.34]} />
      <mesh material={nodes['086'].material} geometry={nodes['086'].geometry} position={[4.73, 38.98, -6.34]} />
      <mesh material={nodes.L11.material} geometry={nodes.L11.geometry} position={[0.09, 38.98, 0.01]} />
      <mesh material={nodes.LF11.material} geometry={nodes.LF11.geometry} position={[-2.79, 38.98, 0.02]} />
      <mesh material={nodes.S11.material} geometry={nodes.S11.geometry} position={[2.98, 38.98, -0.03]} />
      <mesh material={nodes['071'].material} geometry={nodes['071'].geometry} position={[6.67, 36.38, 0]} />
      <mesh material={nodes['072'].material} geometry={nodes['072'].geometry} position={[4.73, 36.38, 6.39]} />
      <mesh material={nodes['073'].material} geometry={nodes['073'].geometry} position={[-4.55, 36.38, 6.39]} />
      <mesh material={nodes['074'].material} geometry={nodes['074'].geometry} position={[-6.5, 36.38, 0.02]} />
      <mesh material={nodes['075'].material} geometry={nodes['075'].geometry} position={[-4.55, 36.38, -6.34]} />
      <mesh material={nodes['076'].material} geometry={nodes['076'].geometry} position={[4.73, 36.38, -6.34]} />
      <mesh material={nodes.L10.material} geometry={nodes.L10.geometry} position={[0.09, 36.38, 0.01]} />
      <mesh material={nodes.LF10.material} geometry={nodes.LF10.geometry} position={[-2.79, 36.38, 0.02]} />
      <mesh material={nodes.S10.material} geometry={nodes.S10.geometry} position={[2.98, 36.38, -0.03]} />
      <mesh material={nodes['061'].material} geometry={nodes['061'].geometry} position={[6.67, 33.78, 0]} />
      <mesh material={nodes['062'].material} geometry={nodes['062'].geometry} position={[4.73, 33.78, 6.39]} />
      <mesh material={nodes['063'].material} geometry={nodes['063'].geometry} position={[-4.55, 33.78, 6.39]} />
      <mesh material={nodes['064'].material} geometry={nodes['064'].geometry} position={[-6.5, 33.78, 0.02]} />
      <mesh material={nodes['065'].material} geometry={nodes['065'].geometry} position={[-4.55, 33.78, -6.34]} />
      <mesh material={nodes['066'].material} geometry={nodes['066'].geometry} position={[4.73, 33.78, -6.34]} />
      <mesh material={nodes.L09.material} geometry={nodes.L09.geometry} position={[0.09, 33.78, 0.01]} />
      <mesh material={nodes.LF9.material} geometry={nodes.LF9.geometry} position={[-2.79, 33.78, 0.02]} />
      <mesh material={nodes.S09.material} geometry={nodes.S09.geometry} position={[2.98, 33.78, -0.03]} />
      <mesh material={nodes['051'].material} geometry={nodes['051'].geometry} position={[6.67, 31.18, 0]} />
      <mesh material={nodes['052'].material} geometry={nodes['052'].geometry} position={[4.73, 31.18, 6.39]} />
      <mesh material={nodes['053'].material} geometry={nodes['053'].geometry} position={[-4.55, 31.18, 6.39]} />
      <mesh material={nodes['054'].material} geometry={nodes['054'].geometry} position={[-6.5, 31.18, 0.02]} />
      <mesh material={nodes['055'].material} geometry={nodes['055'].geometry} position={[-4.55, 31.18, -6.34]} />
      <mesh material={nodes['056'].material} geometry={nodes['056'].geometry} position={[4.73, 31.18, -6.34]} />
      <mesh material={nodes.L08.material} geometry={nodes.L08.geometry} position={[0.09, 31.18, 0.01]} />
      <mesh material={nodes.LF8.material} geometry={nodes.LF8.geometry} position={[-2.79, 31.18, 0.02]} />
      <mesh material={nodes.S08.material} geometry={nodes.S08.geometry} position={[2.98, 31.18, -0.03]} />
      <mesh material={nodes['041'].material} geometry={nodes['041'].geometry} position={[6.67, 28.58, 0]} />
      <mesh material={nodes['042'].material} geometry={nodes['042'].geometry} position={[4.73, 28.58, 6.39]} />
      <mesh material={nodes['043'].material} geometry={nodes['043'].geometry} position={[-4.55, 28.58, 6.39]} />
      <mesh material={nodes['044'].material} geometry={nodes['044'].geometry} position={[-6.5, 28.58, 0.02]} />
      <mesh material={nodes['045'].material} geometry={nodes['045'].geometry} position={[-4.55, 28.58, -6.34]} />
      <mesh material={nodes['046'].material} geometry={nodes['046'].geometry} position={[4.73, 28.58, -6.34]} />
      <mesh material={nodes.L07.material} geometry={nodes.L07.geometry} position={[0.09, 28.58, 0.01]} />
      <mesh material={nodes.LF7.material} geometry={nodes.LF7.geometry} position={[-2.79, 28.58, 0.02]} />
      <mesh material={nodes.S07.material} geometry={nodes.S07.geometry} position={[2.98, 28.58, -0.03]} />
      <mesh material={nodes['031'].material} geometry={nodes['031'].geometry} position={[6.67, 25.98, 0]} />
      <mesh material={nodes['032'].material} geometry={nodes['032'].geometry} position={[4.73, 25.98, 6.39]} />
      <mesh material={nodes['033'].material} geometry={nodes['033'].geometry} position={[-4.55, 25.98, 6.39]} />
      <mesh material={nodes['034'].material} geometry={nodes['034'].geometry} position={[-6.5, 25.98, 0.02]} />
      <mesh material={nodes['035'].material} geometry={nodes['035'].geometry} position={[-4.55, 25.98, -6.34]} />
      <mesh material={nodes['036'].material} geometry={nodes['036'].geometry} position={[4.73, 25.98, -6.34]} />
      <mesh material={nodes.L06.material} geometry={nodes.L06.geometry} position={[0.09, 25.98, 0.01]} />
      <mesh material={nodes.LF6.material} geometry={nodes.LF6.geometry} position={[-2.79, 25.98, 0.02]} />
      <mesh material={nodes.S06.material} geometry={nodes.S06.geometry} position={[2.98, 25.98, -0.03]} />
      <mesh material={nodes['021'].material} geometry={nodes['021'].geometry} position={[6.67, 23.38, 0]} />
      <mesh material={nodes['022'].material} geometry={nodes['022'].geometry} position={[4.73, 23.38, 6.39]} />
      <mesh material={nodes['023'].material} geometry={nodes['023'].geometry} position={[-4.55, 23.38, 6.39]} />
      <mesh material={nodes['024'].material} geometry={nodes['024'].geometry} position={[-6.5, 23.38, 0.02]} />
      <mesh material={nodes['025'].material} geometry={nodes['025'].geometry} position={[-4.55, 23.38, -6.34]} />
      <mesh material={nodes['026'].material} geometry={nodes['026'].geometry} position={[4.73, 23.38, -6.34]} />
      <mesh material={nodes.L05.material} geometry={nodes.L05.geometry} position={[0.09, 23.38, 0.01]} />
      <mesh material={nodes.LF5.material} geometry={nodes.LF5.geometry} position={[-2.79, 23.38, 0.02]} />
      <mesh material={nodes.S05.material} geometry={nodes.S05.geometry} position={[2.98, 23.38, -0.03]} />
      <mesh material={nodes['011'].material} geometry={nodes['011'].geometry} position={[6.67, 20.78, 0]} />
      <mesh material={nodes['012'].material} geometry={nodes['012'].geometry} position={[4.73, 20.78, 6.39]} />
      <mesh material={nodes['013'].material} geometry={nodes['013'].geometry} position={[-4.55, 20.78, 6.39]} />
      <mesh material={nodes['014'].material} geometry={nodes['014'].geometry} position={[-6.5, 20.78, 0.02]} />
      <mesh material={nodes['015'].material} geometry={nodes['015'].geometry} position={[-4.55, 20.78, -6.34]} />
      <mesh material={nodes['016'].material} geometry={nodes['016'].geometry} position={[4.73, 20.78, -6.34]} />
      <mesh material={nodes.L04.material} geometry={nodes.L04.geometry} position={[0.09, 20.78, 0.01]} />
      <mesh material={nodes.LF4.material} geometry={nodes.LF4.geometry} position={[-2.79, 20.78, 0.02]} />
      <mesh material={nodes.S04.material} geometry={nodes.S04.geometry} position={[2.98, 20.78, -0.03]} />
      <mesh material={nodes['009'].material} geometry={nodes['009'].geometry} position={[-4.48, 17.39, -4.54]} />
      <mesh material={nodes['010'].material} geometry={nodes['010'].geometry} position={[4.66, 17.39, -4.6]} />
      <mesh material={nodes['007'].material} geometry={nodes['007'].geometry} position={[4.66, 17.39, 4.61]} />
      <mesh material={nodes['008'].material} geometry={nodes['008'].geometry} position={[-4.48, 17.39, 4.57]} />
      <mesh material={nodes.LF3.material} geometry={nodes.LF3.geometry} position={[-2.79, 17.39, 0.02]} />
      <mesh material={nodes.L03.material} geometry={nodes.L03.geometry} position={[0.1, 17.39, 0.01]} />
      <mesh material={nodes.S03.material} geometry={nodes.S03.geometry} position={[2.98, 17.39, -0.03]} />
      <mesh material={nodes.BC2.material} geometry={nodes.BC2.geometry} position={[0.09, 13.18, -1.75]} />
      <mesh material={nodes.L2E.material} geometry={nodes.L2E.geometry} position={[8.36, 13.18, 7.58]} />
      <mesh material={nodes['006'].material} geometry={nodes['006'].geometry} position={[-4.6, 13.18, 6.86]} />
      <mesh material={nodes.LF2.material} geometry={nodes.LF2.geometry} position={[-2.79, 13.18, 0.02]} />
      <mesh material={nodes.L02.material} geometry={nodes.L02.geometry} position={[0.1, 13.18, 0.01]} />
      <mesh material={nodes.S02.material} geometry={nodes.S02.geometry} position={[2.98, 13.18, -0.03]} />
      <mesh material={nodes.WB2.material} geometry={nodes.WB2.geometry} position={[2.85, 13.18, 7.58]} />
      <mesh material={nodes.L1E.material} geometry={nodes.L1E.geometry} position={[5.61, 9.94, 7.58]} />
      <mesh material={nodes['002'].material} geometry={nodes['002'].geometry} position={[-4.6, 9.94, 6.86]} />
      <mesh material={nodes.LF1.material} geometry={nodes.LF1.geometry} position={[-2.79, 9.94, 0.02]} />
      <mesh material={nodes.L01.material} geometry={nodes.L01.geometry} position={[0.1, 9.94, 0.01]} />
      <mesh material={nodes.S01.material} geometry={nodes.S01.geometry} position={[2.98, 9.94, -0.03]} />
      <mesh material={nodes['003'].material} geometry={nodes['003'].geometry} position={[-7.61, 9.94, 0.02]} />
      <mesh material={nodes['004'].material} geometry={nodes['004'].geometry} position={[-5.42, 9.94, -7.53]} />
      <mesh material={nodes['005'].material} geometry={nodes['005'].geometry} position={[5.61, 9.94, -7.53]} />
      <mesh material={nodes.CR1.material} geometry={nodes.CR1.geometry} position={[7.78, 9.94, 0.02]} />
      <mesh material={nodes.S0E.material} geometry={nodes.S0E.geometry} position={[8.36, 7.44, 7.58]} />
      <mesh material={nodes.MRW.material} geometry={nodes.MRW.geometry} position={[-4.6, 7.44, 6.86]} />
      <mesh material={nodes.LF0.material} geometry={nodes.LF0.geometry} position={[-2.79, 7.44, 0.02]} />
      <mesh material={nodes.LB0.material} geometry={nodes.LB0.geometry} position={[0.1, 7.44, 0.01]} />
      <mesh material={nodes.NU0.material} geometry={nodes.NU0.geometry} position={[-2.93, 7.44, -4.64]} />
      <mesh material={nodes.CR0.material} geometry={nodes.CR0.geometry} position={[7.78, 7.44, 0.02]} />
      <mesh material={nodes.L0E.material} geometry={nodes.L0E.geometry} position={[2.85, 7.44, 7.58]} />
      <mesh material={nodes.OWN.material} geometry={nodes.OWN.geometry} position={[-13.45, 7.44, -7.53]} />
      <mesh material={nodes.OWS.material} geometry={nodes.OWS.geometry} position={[-13.45, 7.44, 0.02]} />
      <mesh material={nodes['00N'].material} geometry={nodes['00N'].geometry} position={[0.14, 7.44, -16.1]} />
      <mesh
        material={nodes['00W'].material}
        geometry={nodes['00W'].geometry}
        position={[-15.24, 7.44, -0.41]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        material={nodes['00S'].material}
        geometry={nodes['00S'].geometry}
        position={[0.14, 7.44, 16.18]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        material={nodes['00E'].material}
        geometry={nodes['00E'].geometry}
        position={[16.24, 7.44, 0.04]}
        rotation={[0, -1.57, 0]}
      />
    </group>
  )
}

useGLTF.preload('/Grenfell_Tower_Selection_Areas.glb')
