/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/site_texture.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={nodes.Grenfell_Walk_cutter.material}
        geometry={nodes.Grenfell_Walk_cutter.geometry}
      />
      <mesh material={materials.branches} geometry={nodes.CUtree.geometry} />
      <mesh material={materials.leaves} geometry={nodes.CUtree_1.geometry} />
      <group position={[-1, 0, 0]}>
        <mesh
          material={materials.satellite}
          geometry={nodes.Plane015.geometry}
        />
        <mesh
          material={materials["base.006"]}
          geometry={nodes.Plane015_1.geometry}
        />
      </group>
      <mesh
        material={materials["Aldridge Academy Wall"]}
        geometry={nodes.Aldridge_Retaining_Wall.geometry}
        position={[12.08, 8.35, -25.46]}
        rotation={[0, -0.14, 0]}
      />
      <mesh
        material={materials["Central Terrain.001"]}
        geometry={nodes.Central_Terrain.geometry}
      />
      <mesh material={materials.Walkway} geometry={nodes.Columns.geometry} />
      <mesh
        material={materials["Material.001"]}
        geometry={nodes.Cube.geometry}
        position={[-55.82, 6.86, -24.14]}
        rotation={[0, -Math.PI / 5, 0]}
      />
      <mesh
        material={materials["End Wall"]}
        geometry={nodes.End_Wall_East.geometry}
        position={[29.23, 13.88, 37.63]}
        rotation={[0, -0.02, 0]}
      />
      <mesh
        material={materials["End Wall"]}
        geometry={nodes.End_Wall_Mid.geometry}
        position={[-14.22, 14.19, 33.12]}
        rotation={[0, -Math.PI / 9, 0]}
      />
      <mesh
        material={materials["End Wall"]}
        geometry={nodes.End_Wall_North.geometry}
        position={[-54.33, 14.19, 15.27]}
        rotation={[0, -Math.PI / 5, 0]}
      />
      <mesh
        material={materials["satellite close.001"]}
        geometry={nodes.Grenfell_Tower_Terrain.geometry}
      />
      <group position={[6.84, 18.98, 31.05]}>
        <mesh
          material={materials["Lowrise Trim"]}
          geometry={nodes.Cube005.geometry}
        />
        <mesh
          material={materials["Lowrise Blocks"]}
          geometry={nodes.Cube005_1.geometry}
        />
        <mesh
          material={materials["Lowrise Walls"]}
          geometry={nodes.Cube005_2.geometry}
        />
        <mesh
          material={materials["Lowrise Windows"]}
          geometry={nodes.Cube005_3.geometry}
        />
        <mesh
          material={materials["Lowrise Roofs"]}
          geometry={nodes.Cube005_4.geometry}
        />
      </group>
      <group position={[6.84, 18.98, 31.05]}>
        <mesh
          material={materials["Lowrise Trim"]}
          geometry={nodes.Cube006.geometry}
        />
        <mesh
          material={materials["Lowrise Blocks"]}
          geometry={nodes.Cube006_1.geometry}
        />
        <mesh
          material={materials["Lowrise Walls"]}
          geometry={nodes.Cube006_2.geometry}
        />
        <mesh
          material={materials["Lowrise Windows"]}
          geometry={nodes.Cube006_3.geometry}
        />
        <mesh
          material={materials["Lowrise Roofs"]}
          geometry={nodes.Cube006_4.geometry}
        />
      </group>
      <mesh
        material={materials["Lowrise Walls"]}
        geometry={nodes.lowrise_west_wall.geometry}
        position={[-5.86, 10.55, 19.57]}
      />
      <group position={[21.28, 18.33, 31.39]}>
        <mesh
          material={materials["Lowrise Trim"]}
          geometry={nodes.Cube007.geometry}
        />
        <mesh
          material={materials.Walkway}
          geometry={nodes.Cube007_1.geometry}
        />
      </group>
      <group position={[-7.52, 18.33, 31.02]}>
        <mesh
          material={materials["Lowrise Trim"]}
          geometry={nodes.Cube007.geometry}
        />
        <mesh
          material={materials.Walkway}
          geometry={nodes.Cube007_1.geometry}
        />
      </group>
      <group position={[-19.55, 18.33, 26.55]} rotation={[0, -Math.PI / 9, 0]}>
        <mesh
          material={materials["Lowrise Trim"]}
          geometry={nodes.Cube007.geometry}
        />
        <mesh
          material={materials.Walkway}
          geometry={nodes.Cube007_1.geometry}
        />
      </group>
      <group position={[-47.3, 18.36, 15.73]} rotation={[0, -Math.PI / 9, 0]}>
        <mesh
          material={materials["Lowrise Trim"]}
          geometry={nodes.Cube007.geometry}
        />
        <mesh
          material={materials.Walkway}
          geometry={nodes.Cube007_1.geometry}
        />
      </group>
      <mesh
        material={materials.Walkway}
        geometry={nodes.walkway.geometry}
        position={[34.04, 11.6, 25.74]}
      />
      <mesh
        material={materials["Walkway Balustrade"]}
        geometry={nodes.walkway_balustrade.geometry}
        position={[-9.86, 11.6, 13.15]}
      />
      <mesh
        material={materials.Walkway}
        geometry={nodes.walkway001.geometry}
        position={[34.04, 11.6, 25.74]}
      />
      <mesh
        material={materials["Outer Terrain"]}
        geometry={nodes["BuildingMesh-00448003"].geometry}
        position={[0, 0, 1.15]}
      />
      <mesh
        material={materials["Intermediate Terrain"]}
        geometry={nodes.Intermediate_Terrain.geometry}
      />
    </group>
  );
}

useGLTF.preload("/site.glb");
